Atualiza documentação
rennerocha/querido-diario-api-wrapper pull request #4
Opened 2022-08-26 15:39 UTC by trevineju

Buscando se adequar ao padrão de documentação adotado no projeto (#https://github.com/okfn-brasil/querido-diario-comunidade/issues/14), este PR:

- Cria diretório / .github
- Adiciona CODE_OF_CONDUCT.md e sua tradução em inglês. Eles apontam para os de Comunidade
- Adiciona CONTRIBUTING.md e sua tradução em inglês. Eles apontam para os de Comunidade
- Adiciona FUNDING.yml
- Adiciona SUPPORT.md e sua tradução em inglês
- Atualiza e move LICENSE.md da raiz para /.github

2023-03-06 20:27 UTC, trevineju commented on docs/README.md
> +Para utilizar a biblioteca `querido_diario` é necessário ter [Python](https://docs.python.org/3.8/) (3.8+) instalado.
Copiei isto do repo da toolbox, não sei qual versão de python a biblioteca é compatível. Deixei aqui pra poder fazer esse comentário. É o caso de avaliar ou omitir esse parênteses

2023-04-19 16:18 UTC, ogecece requested changes
Subi código pra permitir deixar a parte de contribuição da api-wrapper e da toolbox bem similar. Pode dar uma olhada? Só não tem nada de tesseract ou tabula.

De resto, as mudanças que eu pediria aqui são as mesmas da revisão da toolbox

2023-04-19 16:18 UTC, ogecece commented on docs/README.md
> +Para utilizar a biblioteca `querido_diario` é necessário ter [Python](https://docs.python.org/3.8/) (3.8+) instalado.
provavelmente 3.7+ por conta da `requests` mas como o ambiente que tô testando aqui é 3.8 pode ser 3.8 por enquanto mesmo e depois testar se 3.7 tá ok

2023-04-26 18:20 UTC, trevineju commented
Repliquei as mudanças solicitadas em `-toolbox` aqui. Aproveitei e adicionei os shields de pyhton e pypi que tem lá na toolbox e não tem aqui. O shield de "Python Version" não funcionou corretamente.

2023-08-03 16:10 UTC, ogecece approved these changes
LGTM!

O shield da versão do Python vai ser corrigido quando a versão nova ficar disponível no PyPI.

2023-08-10 20:02 UTC, merged